#!/bin/sh

waitron wm_config border_width 4
waitron wm_config color_focused 0x4265f4
waitron wm_config color_unfocused 0x393638
waitron wm_config gap_width all 20
waitron wm_config grid_gap_width 20
waitron wm_config cursor_position middle
waitron wm_config groups_nr 4
waitron wm_config enable_sloppy_focus false
waitron wm_config sticky_windows true
waitron wm_config enable_borders true

